### ISSUE TITLE
No signature of method  error

### ISSUE THREAD

**Issue by mugunthan74** [tommysqueak/qubino-flush-shutter#1]
Hi I am new to this and when I create this in the "from code" and press Create I get the bleow error in red, please help.
thx

No signature of method: script_app_metadata_c724c557_eb89_4e4a_83b8_0dcd6dc6614c.metadata() is applicable for argument types: (script_app_metadata_c724c557_eb89_4e4a_83b8_0dcd6dc6614c$_run_closure1) values: [script_app_metadata_c724c557_eb89_4e4a_83b8_0dcd6dc6614c$_run_closure1@10ee1403] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by tommysqueak** [comment]
Hi,

I just double checked and created a handler from my code, using the 'from code' method and it created successfully.

I'm not sure what the issue could be. Here's some basic checks. Maybe these are obvious and you've already done this but worth outlining just in case they help, in the some form.

* Check it's the full file you've copied, from https://raw.githubusercontent.com/tommysqueak/qubino-flush-shutter/master/devicetypes/tommysqueak/qubino-flush-shutter.src/qubino-flush-shutter.groovy Maybe some part was missing.
* Check it's a handler that's being created and not a smartapp.
* Check the device handler is not already created or listed in your device handler list. https://graph-eu01-euwest1.api.smartthings.com/ide/devices

Are you creating this in the eu part of smarthings eg graph-eu01...? I believe there's a us version that has a slightly different interface.

**Comment by mugunthan74** [comment]
Hi Tom, Thank you for the prompt response, yes i was trying to add it in the “Smartapps” since you mentioned it here I have successfully added to “device Handler”

After that do I have to do anything else?  I will be getting my Qubino Flush shutter on Monday.

Sorry about that as i am new to this and never done anything like this before and I couldn’t find any instructions to do this.


Kind Regards
Mugun

**Comment by tommysqueak** [comment]
no probs, happy to help :)

Now that you have the device saved and published (did you 'publish for me'?), when you add the qubino device to smartthings (I think the instructions come with the qubino, on how to put it into inclusion mode, so it can be added to the hub) it should automatically pick up this handler as the one to use for the qubino module. If it doesn't and discovers it as some generic z-wave shutter handler, you can come back https://graph-eu01-euwest1.api.smartthings.com/device/list and change your device it to use this handler instead.

Feel free to reach out, if you get stuck.

**Comment by mugunthan74** [comment]
Hi Tom, I got everything setup but I am having trouble closing if fully as its only moves 25cm and stops, I figured out that 25cm is your custom level 1  so I have changed all the figures says 25 to 75 but still not changing anything.

Can you help please.

Kind Regards
Mugun

**Comment by tommysqueak** [comment]
The custom levels are quick actions, you can take to move the shutter to a certain preset percentage. So there's some 25%, 50% ones already setup. They don't affect anything beyond that.

It might be that you have to calibrate the qubino first. So that it can figure out what 100% (full open) and 0% (full closed) is. If you click the map looking button (cross and some dashes), the shutter should close and open a couple of times, whilst the qubino figures out those 0% and 100%'s.

**Comment by mugunthan74** [comment]
Hi Tom Thanks for the reply and when i press the Calibration button it moved little bit maybe 25cm and then came back where it started from. 

My shutter control is Zwave plus do you think because of that?

Kind Regards
Mugun

**Comment by tommysqueak** [comment]
I thought you had the Qubino flush shutter module. Did I get that right? I have the qubino module and it's a z-wave plus version.

**Comment by mugunthan74** [comment]
Hi Tom, its i have Qubino Flush Shutter Zwave Plus 240v model not the dc model.

Kind Regards
Mugun

**Comment by tommysqueak** [comment]
I have the same qubino module. Do you know much about the model of your shutters? There's some parameters that can be set on the qubino module. Eg my shutters switch off their motors when it reaches it's closed and opened limits. The qubino detects this by detecting that it's drawing less than 10 watts of power (that's at least how I interpreted 'limit switches'). Yours might be different.

Here's some of the parameters that might be useful for your scenario, taken from the qubino shutter manual.

There's this handler that you can replace with the one you're currently using. It will allow you to tweak the below parameters to troubleshoot the shutters and qubino. I've not used it before, so I can't advise but maybe it'll help.

https://github.com/codersaur/SmartThings/tree/master/devices/zwave-tweaker#changing-a-device-parameter


Parameter no. 74 – Motor moving up/down time
This parameter defines Shutter motor moving time of complete opening or complete closing. Available configuration parameters (data type is 2 Byte DEC):
 default value 0
 0 – moving time disabled (working with limit switches)
 1 - 32767 = 0,1seconds - 3276,7seconds
After that time motor is stopped (relay goes to off state)
NOTE: Important is that the reference position to manually set moving time is always Shutter lower position!
Set parameter 74 to 0 and move the Shutter (using up/down push buttons or main controller UI) to the lowest desired position. On this Shutter position, set parameter 74 to time for complete opening or complete closing. At this point Shutter can be moved up (open) for set time, but can't be moved down because this position is already set as lower Shutter position.
To change Shutter lower position below already set (manual recalibration), parameter 74 must be set to 0 and repeat the procedure described above.
In case Shutter has limit switches, but anyhow you would like to limit opening/closing position by time, you can still do it. In case you put time that is longer that opening/closing real time limited by limit switches, Shutter will stop at limit switch, but the module relay will switch off after define time, not by Shutter limit switch. Take in consideration that in this condition, the positioning with slider through UI will not show correct Shutter position.
Parameter no. 76 - Motor operation detection
Power threshold to be interpreted when motor reach the limit switch. Available configuration parameters (data type is 1 Byte DEC):
 default value 10 = 10W
 0 - 127 = 1-127 W. The value 0 means reaching a limit switch will not be detected.


Possibly these too, but I'm less sure:

Parameter no. 85 – Power consumption max delay time
This parameter defines the max time before motor power
consumption is read after one of the relays is switched ON. If there is no power consumption during this max time (motor not connected, damaged or requires higher time to start, motor in end position) the relay will switch OFF. Time is defined by entering it manually. Available configuration parameters (data type is 1 Byte DEC):
 default value 0 = time is set automatically
 3 - 50 = 0,3seconds - 5seconds (100ms resolution) Parameter no. 90 – Time delay for next motor movement
This parameter defines the minimum time delay between next motor movement (minimum time between switching motor off and on again). Available configuration parameters (data type is 1 Byte DEC):
 default value 5 = 500ms
 1 - 30 = 0,1seconds - 3seconds (100ms resolution)

**Comment by mugunthan74** [comment]
Yep, After following your suggestions it works perfectly 👍🏼👌

**Comment by tommysqueak** [comment]
Great news :)

Which part of the suggestion worked?

**Comment by mugunthan74** [comment]
Line 74= motor moving up/down time to 80
Line 76= 10w

This is the rail & motor I used and it works great, i have scheduled time in smartthings to open the curtain at 8am and close at 5pm and it works perfectly.

Curtain rail Dooya 
Motor Sunflower Kt52E
